[package]
name = "trabalho-2-simulador-de-carro-iago-matos-e-alexia-naara"
version = "0.1.0"
edition = "2021"

[dependencies]
bmp280 = "0.4.0"
i2cdev = "0.6.1"
rppal = { version = "0.22.1", features = ["hal"] }
ctrlc = "3.1"
embedded-graphics = "0.8.1"
ssd1306 = "0.9.0"