[package]
name = "trabalho-2-simulador-de-carro-iago-matos-e-alexia-naara"
version = "0.1.0"
edition = "2021"

[dependencies]
bmp280 = "0.4.0"
i2cdev = "0.4.4"
linux-embedded-hal = "0.4.0"
rppal = "0.18.0"
ctrlc = "3.1"
